### ISSUE TITLE
BDD test fails if cloud APP is ued

### ISSUE THREAD

**Issue by LihengGong** [orders-squad/orders#166]
**As a** developer
**I need** run BDD using bluemix URL
**So that** the behavior of Cloud APP is tested

**Assumptions:** 
* Bluemix APP works fine
**Acceptance Criteria:**
```
Given Bluemix APP and its URL
When BDD is run
Then tests should pass
```

**Comment by LihengGong** [comment]
>Scenario: Create an Order                 # features/order.feature:18
    Given the following orders              # features/steps/order_steps.py:19 0.894s
      | cust_id | prod_id | prod_name | prod_qty | prod_price | status  |
      | 1       | 1       | echo dot  | 2        | 50.5       | ordered |
      | 2       | 2       | kindle    | 3        | 40.5       | ordered |
      | 3       | 3       | backpack  | 1        | 23.4       | ordered |
    When I visit the "Home Page"            # features/steps/order_steps.py:41 0.113s
    And I set the "product_id" to "1"       # features/steps/order_steps.py:56 20.191s
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "features/steps/order_steps.py", line 67, in step_impl
          element = context.driver.find_element_by_id(element_id)
        File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 271, in find_element_by_id
          return self.find_element(by=By.ID, value=id_)
        File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 756, in find_element
          'value': value})['value']
        File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
          self.error_handler.check_response(response)
        File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
          raise exception_class(message, screen, stacktrace)
      NoSuchElementException: Message: {"errorMessage":"Unable to find element with id 'item_product_id'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"96","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:34746","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{"using": "id", "sessionId": "604da230-fe41-11e8-adaf-3de2f25b3b50", "value": "item_product_id"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/604da230-fe41-11e8-adaf-3de2f25b3b50/element"}}
      Screenshot: available via screen

**Comment by LihengGong** [comment]
Reproduce steps:
1. Set baseurl to BASE_URL = https://nyu-order-service-f18.mybluemix.net/
2. Run BDD
3. Test fails.

**Comment by LihengGong** [comment]
OK, we found the root cause: in url, HTTP should be used instead of HTTPs
