### ISSUE TITLE
bluemix pipeline test failure - Expected environment variable 'DB_NAME' not set.

### ISSUE THREAD

**Issue by LihengGong** [orders-squad/orders#99]
**As a** developer
**I need** bluemix to run test code
**So that** code is properly tested

**Assumptions:** 
* Bluemix is correctly set up.

**Acceptance Criteria:**
```
Given bluemix and test code
When code is delopyed
Then test can run successfully
```

Error message:
```
======================================================================
ERROR: Failure: Exception (Expected environment variable 'DB_NAME' not set.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/pipeline/a6fb9941-a993-4ce0-b571-096cf5b84cbf/app/__init__.py", line 25, in <module>
    DB_NAME = get_env_variable('DB_NAME')
  File "/home/pipeline/a6fb9941-a993-4ce0-b571-096cf5b84cbf/app/__init__.py", line 22, in get_env_variable
    raise Exception(message)
Exception: Expected environment variable 'DB_NAME' not set.
```

**Comment by LihengGong** [comment]
Should be related to env variables.

**Comment by LihengGong** [comment]
Trying to add env variables in Bluemix pipeline.
